version: "3.8"

services:
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn start:dev"
    depends_on:
      - db
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      HOST: db
      PORT: 5432
      PASSWORD: postgres
      USERNAME: postgres
      DB_NAME: book_store
    links:
      - "db"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_store
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
